services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_NAME: shopdb
      DB_USER: shopuser
      DB_PASSWORD: shoppass
      DB_HOST: db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shopdb
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


